services:
  statuspages_bot:
    build:
      dockerfile: './dockerfile'
      args:
        DAEMON_ENABLED: ${DAMEON_ENABLED:-false}
        DAEMON_FREQUENCY: ${DAEMON_FREQUENCY:-30s}
        DAEMON_EXECUTION_TIMEOUT: ${DAEMON_EXECUTION_TIMEOUT:-30m}
        DISCORD_TOKEN: ${DISCORD_TOKEN}
        DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
        DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
        DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
        DISCORD_UPDATE_ROLE_ID: ${DISCORD_UPDATE_ROLE_ID}
        DISCORD_SHOULD_CROSSPOST: ${DISCORD_SHOULD_CROSSPOST:-true}
        STATUSPAGE_API_KEY: ${STATUSPAGE_API_KEY}
        STATUSPAGE_PAGE_ID: ${STATUSPAGE_PAGE_ID}
        STATUSPAGE_URL: ${STATUSPAGE_URL:-status.ticketsbot.cloud}
        SERVER_ADDR: ${SERVER_ADDR:-8080}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD:-null}
        DATABASE_URI: ${DATABASE_URI:-postgres://postgres:${DATABASE_PASSWORD:-null}@postgres-statusbot:5432/postgres}
        JSON_LOGS: ${JSON_LOGS:-false}
        LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      # change the ports below to reflect your SERVER_ADDR env variable!
        - '${SERVER_ADDR:-8080}:${SERVER_ADDR:-8080}'
    depends_on:
        postgres:
          condition: service_healthy
          restart: true
    networks:
        - app-network

  postgres:
    image: postgres:15
    container_name: postgres-statusbot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-null}
      POSTGRES_DB: statusbot
    ports: # Uncomment this line and the following line to access the main postgres on port 5433. Do not change the second port (5432) otherwise you cannot access the DB
      - "5433:5432"
    volumes:
      - ./pgstatusbotdb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d statusbot -c 'SELECT 1' > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge
